#!/usr/bin/env ruby

system 'script/bootstrap'

require 'json'
require 'erb'
require 'uglifier'
require './lib/octo_extractor'

puts "===> Extracting data from Octokit.rb to build/data.json"
Proc.new do
	File.write "build/data.json", OctoExtractor.build_extension_data.to_json
end.call

puts "===> Building inject.js"
Proc.new do
	@data = File.read 'build/data.json'
	template_string = File.read 'src/inject.js.erb'
	template = ERB.new template_string
	doc_injector_src = template.result
	File.write "build/inject.js", doc_injector_src
	File.write "build/octodoctotron/inject.js", doc_injector_src
end.call
